// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./components/CodeEditor/CodeEditor.vue')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    Three: typeof import('./components/Three/Three.vue')['default']
    WindowBox: typeof import('./components/WindowBox.vue')['default']
  }
}
