// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./components/CodeEditor/CodeEditor.vue')['default']
    GLSLPreview: typeof import('./components/Three/GLSLPreview.vue')['default']
    ICarbonUpdateNow: typeof import('~icons/carbon/update-now')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    KPopover: typeof import('@0x-jerry/vue-kit')['KPopover']
    KSwitch: typeof import('@0x-jerry/vue-kit')['KSwitch']
    WindowBox: typeof import('./components/WindowBox.vue')['default']
  }
}
